### ISSUE TITLE
Front page loads too many posts too quickly

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#288]
It loads new post quicker than a person scrolls, this makes it very buggy and slow. It should load only when a person scrolls down. Please fix this asap and push to live.

**Comment by dpatil-gmcs** [comment]
@MSchirp  Can you please give some more details?
By new post do you mean the infinite scroll on home page?

**Comment by MSchirp** [comment]
Yes sorry. The infinite scroll on the front page loads too many posts too fast. It should load a new page only when a user is around 80% down, and then only a few posts more. Only when the user is 80% on that page, it should load a new post etc. Now it loads tons of new articles unnecessarily, which is slow and not a good experience.

**Comment by dpatil-gmcs** [comment]
@MSchirp  We have implemented the required infinite scroll effect and committed the code to the TEST site.
Please have a look and let us know your views on it!

**Comment by MSchirp** [comment]
Please push it to live and let me know on Slack the moment you've done this. Since the test homepage is still not working for me, I can't test there.

**Comment by dpatil-gmcs** [comment]
@MSchirp  This fix, is deployed to the LIVE, now you will be able to see the changes on the LIVE site. Please have a look and let us know your views on it.

**Comment by MSchirp** [comment]
Much better, thanks!
